# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'malt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for malt
pod 'Firebase/Analytics'
pod 'Firebase/Database'
pod 'Firebase/Firestore'



  target 'maltTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'maltUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
